name: Elixir Tests & Dialyzer
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        otp: ['23.3']
        elixir: ['1.10', '1.12.2']

    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Retrieve Mix Dependencies Cache
        uses: actions/cache@v1
        id: mix-cache
        with:
          path: deps
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - name: Install Mix Dependencies
        if: steps.mix-cache.outputs.cache-hit != 'true'
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get

      - name: Compile
        run: MIX_ENV=test mix compile --warnings-as-errors

      - name: Retrieve PLT Cache
        uses: actions/cache@v1
        id: plt-cache
        with:
          path: priv/plts
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-plts-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - name: Run credo
        run: MIX_ENV=test mix credo --strict
        if: matrix.elixir == '1.12.2'

      - name: Run dialyzer
        run: MIX_ENV=test mix dialyzer --halt-exit-status
        if: matrix.elixir == '1.12.2'

      - name: Run tests
        run: mix test
